### ISSUE TITLE
Doesn't filter short words properly

### ISSUE THREAD

**Issue by kibi** [dokufreaks/plugin-cloud#15]
It seems that option to filter short words doesn't work with letters other than latin. For example russian words "на", "в" and so on stay unfiltered.

**Comment by LarsGit223** [comment]
Does the problem really only happen with non-latin letters? Please see the conversation under #55. Maybe that is related to your problem too.

**Comment by LarsGit223** [comment]
Should be fixed now, tested with "на" and ```minimum_word_length``` set to 3.
