### ISSUE TITLE
tagcloud by namespace recursively

### ISSUE THREAD

**Issue by joemouth** [dokufreaks/plugin-cloud#17]
It would be fine to show all tags by a namespace and its subnamespaces/subpages

**Comment by rellampec** [comment]
The plugin is awesome. A pity that you cannot restrict the words shown by namespace. Currently, it will show all the most common words in **all the wiki**. So it only makes sense to use it the main namespace and only once in all the wiki; while it could be used in the main page of different namespaces if there was a chance to restrict the words to a namespace(s).

**Comment by Klap-in** [comment]
Filtering on namespace for tag cloud is available.
