### ISSUE TITLE
stopwords are not excluded from tag cloud

### ISSUE THREAD

**Issue by Cantello** [dokufreaks/plugin-cloud#18]
I use a tag cloud for a small wiki, where most entries are categorised by tags. However, I'd like to remove certain common tags from the cloud as these tags have their own pages where they are listed. To achieve this, I have created a conf/stopwords.txt file where I put these common tags (only three of them) and finished with a blank line and saved the file with unix endings (i.e. LF).

Sadly, even after rebuilding the tag index, these words still appear in the cloud. Is there anyplace else, I could look for reasons for this behaviour? I also tried adding the words to inc/lang/en/stopwords, did not work either.

Any hints? Thanks!

Helge.
# 

Dokuwiki Angua RC1, cloud plugin 2009-09-12

**Comment by LarsGit223** [comment]
Yes, from my test I can confirm that the stopwords are only applied to a word cloud. This is confusing. I will mark this as a bug.
