### ISSUE TITLE
Plugin not working with Release 2013-05-10a "Weatherwax"

### ISSUE THREAD

**Issue by qwertz1** [dokufreaks/plugin-cloud#23]
Hi :)

I get the following error when using the plugin.

Syntax used on page:
 ~~TAGCLOUD~~ 

Results in:
Fatal error: Call to undefined method helper_plugin_tag::tagOccurrences() in  urltomywebspace/wiki/lib/plugins/cloud/syntax.php on line 188

In the past it worked great.

**Comment by LarsGit223** [comment]
This was obviously a mismatch between the tag and cloud plugin. IMHO this can be closed now as there was no feedback yet.

If the problem still exists with actual versions of DokuWiki, tag plugin and cloud plugin then please re-open the issue.
