### ISSUE TITLE
Reset the cloud

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [dokufreaks/plugin-cloud#54]
Hi,

a specific namespace of our wiki has changed to another platform. But now the search cloud contains terms which don't have any importance no more. So my idea is to refresh the cloud. But I don't know how to manage this.

Regards Juergen

**Comment by LarsGit223** [comment]
Did you try to clear the cache?
Either with ```&purge=true``` or by emptying the cache folder (haven't tried, just an idea).

**Comment by Juergen-aus-Koeln** [comment]
The normal cache only impacts on the wiki pages, not on the search cloud. So there must be a special file, perhaps in the meta dir, that keeps the information for the search entries.

**Comment by Juergen-aus-Koeln** [comment]
I've found it:
The cloud is build upon the items of the searchstats plugin. And this plugin stores the results in a directory /data/indes/searchstats. Deleting this directory leads to a complete rebuild of the search cloud.
