### ISSUE TITLE
Cloud contains short words

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [dokufreaks/plugin-cloud#55]
Hi,

after rebuild of the cloud there appear words with a length of one or two letters, e.g. "0", "1" or "it". How can I prevent this?

Regards
Juergen

**Comment by Klap-in** [comment]
See configuration manager: 'minimum_word_length'  = 'Minimum word-length for words in the cloud'

**Comment by Juergen-aus-Koeln** [comment]
The parameter is set to "2":
![grafik](https://cloud.githubusercontent.com/assets/1800472/26544420/0a73dc66-4462-11e7-966f-0293b17830b8.png)

But the cloud looks like this:
![grafik](https://cloud.githubusercontent.com/assets/1800472/26544449/255d201e-4462-11e7-935e-a5b66246ad7c.png)

**Comment by Klap-in** [comment]
Maybe your rebuilding is using a different approach...

**Comment by Juergen-aus-Koeln** [comment]
The procedure to reset the cloud was to delete the directory /data/index/searchstats, described in issue  https://github.com/dokufreaks/plugin-cloud/issues/54.
I hope this was the right way (?)

**Comment by Klap-in** [comment]
What happens is you update this number '2' to a higher value?

**Comment by LarsGit223** [comment]
@Juergen-aus-Koeln:
What kind of cloud do you display (```~~CLOUD~~```, ```~~TAGCLOUD~~```, ```~~SEARCHCLOUD~~```)?

I had a quick glance at the code and it looks like that only the word cloud (```~~CLOUD~~```) is checking/using the parameter ```minimum_word_length```.

**Comment by Juergen-aus-Koeln** [comment]
The syntax I use is 
```~~SEARCHCLOUD:30~~```
Changing the parameter 'minimum_word_length' from '2' to '3' brings no changes

**Comment by LarsGit223** [comment]
I wanted to test the ```~~SEARCHCLOUD~~```. Unfortunately I could not install the ```searchstats``` plugin. The link to the repository seems to be invalid. Where have you installed it from?

**Comment by LarsGit223** [comment]
Please ignore my question - found it here on github.

**Comment by LarsGit223** [comment]
It is as I assumed: the searchcloud is actually ignoring the config parameter!
As a quick fix open the file ```syntax.php```, go to line 62. It should look like this:
```php
            } elseif($type == 'search') {
                /** @var helper_plugin_searchstats $helper */
                $helper = plugin_load('helper', 'searchstats');
                if($helper) {
                    $cloud = $helper->getSearchWordArray($num);
                    // calculate min/max values
                    $min = PHP_INT_MAX;
                    $max = 0;
                    foreach ($cloud as $size) {
                        $min = min($size, $min);
                        $max = max($size, $max);
                    }
                } else {
```
Change it to:
```php
            } elseif($type == 'search') {
                /** @var helper_plugin_searchstats $helper */
                $helper = plugin_load('helper', 'searchstats');
                if($helper) {
                    $cloud = $helper->getSearchWordArray($num);

                    foreach ($cloud as $key => $count) {
                        if (strlen($key) < $this->getConf('minimum_word_length')) {
                            unset ($cloud [$key]);
                        }
                    }

                    // calculate min/max values
                    $min = PHP_INT_MAX;
                    $max = 0;
                    foreach ($cloud as $size) {
                        $min = min($size, $min);
                        $max = max($size, $max);
                    }
                } else {
```
I will mark this as a bug. It's less confusing if the config setting is applied to all kinds off clouds.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, this is the solution
