### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by bgx4k3p** [dokufreaks/plugin-cloud#60]
Just updated to the latest plugin and started getting this error showing on top of my pages:

```
Warning: Invalid argument supplied for foreach() in 
/dokuwiki/lib/plugins/cloud/syntax.php on line 198
```

Release 2017-02-19b "Frusterick Manners"

**Comment by LarsGit223** [comment]
Please re-install and re-test. I fixed a missing null pointer check and that hopefully fixes your problem.

**Comment by bgx4k3p** [comment]
Works fine now, no more errors. Thanks for the quick fix!

**Comment by LarsGit223** [comment]
I'm sorry for the inconvenience. Unfortunately I did not see the error in my tests. I assume that this difference might be because of different PHP versions. I use PHP7. Which version do you use?

**Comment by bgx4k3p** [comment]
The built-in PHP in Mac OS X 10.12.6

```
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by LarsGit223** [comment]
Ok, thanks.
