### ISSUE TITLE
Do not work in webserver

### ISSUE THREAD

**Issue by renqiang06** [dokufreaks/plugin-cloud#61]
No cloud or  tagcloud display in webserver(win7 32 apache2.4.23/php 5.6.25)
but it works in local webserver(win7 32 apache2.4.6/php 5.4.17)
Should some sets of webserver be modified to this plugin?
THX

**Comment by LarsGit223** [comment]
When did you install the cloud plugin on the webserver? If it is older than 29 days please re-install it and try again, see issue #60.

**Comment by renqiang06** [comment]
2017.08.27. I had try the release
I think it must be something wrong with my webserver. But i can not find it,cry~~~

**Comment by LarsGit223** [comment]
It could be related to the PHP version.
Can you describe the problem in more detail please:
- do you just see no tags...
- or a completely blank page
- could you get a server log and post it (I assume it would show an error for the cloud plugin)

**Comment by renqiang06** [comment]
Everything is ok but these tags. 
errors as follows,
`[Tue Sep 05 10:59:26.257089 2017] [access_compat:error] [pid 5368:tid 860] [client 10.122.177.199:51583] AH01797: client denied by server configuration: D:/.../Notes/data/security.png, referer: http://10.122.148.155/.../notes/doku.php?id=wiki:site_notice&do=admin <http://10.122.148.155/.../notes/doku.php?id=wiki:site_notice&do=admin>  `

**Comment by LarsGit223** [comment]
I assume this is the access.log. I need an error.log. I hope the file names are the same on windows as on linux.

**Comment by LarsGit223** [comment]
@renqiang06: could you fix the problem? Can this be closed?
