### ISSUE TITLE
Option to style the cloud. Style.less resets after every update.

### ISSUE THREAD

**Issue by tinogithub** [dokufreaks/plugin-cloud#70]
Hi,

until now I changed the style in the style.less file. However after every update the file is being reset. Do I miss the option to style the plugin?

thank you very much. I use the plugin a lot and I like it.

**Comment by LarsGit223** [comment]
Please try to put your styles in the userstyles file, see https://www.dokuwiki.org/devel:css#user_styles. If that works then you can use it. It is part of the config and will not be overwritten by a plugin update.

**Comment by tinogithub** [comment]
Hi LarsGit223,
thank you very much. This solved it.
This feature was new to me.

Case closed.
