### ISSUE TITLE
Update in dokuwiki doesn't work

### ISSUE THREAD

**Issue by jochenwezel** [dokufreaks/plugin-cloud#77]
## Bug
In dokuwiki's extension manager, I update all the several plugins. And it works for all plugins except the cloud plug-in.

## Environment
* dokuwiki HogFather 2020-07-29
* extension manager shows hint "Update: Version 2020-09-27 steht zum Download bereit." at cloug plugin entry
* click at update button 
* plugin updated notification appears on top of page
* butt still the same hint: "Update: Version 2020-09-27 steht zum Download bereit."

## Plugin entry details
```
Status: installiert, deaktiviert, Plugin
Download-URL: github.com/dokufreaks/plugin-cl…archive/2019-02-15.zip
Quelle: github.com/dokufreaks/plugin-cloud/tree/master
Installierte Version: 2019-02-15
Ihr letztes Update: Mon, 09 Nov 2020 16:08:55 +0100
Verfügbare Version: 2020-09-27
Kompatibel mit: "Hogfather" (2020-07-29), "Greebo" (2018-04-22), "Frusterick Manners" (2017-02-19), "Detritus" (2015-08-10), "Hrun" (2014-09-29), "Ponder Stibbons" (2014-05-05)
```

**Comment by splitbrain** [comment]
should be fixed now
