### ISSUE TITLE
PHP8.1 Warning

### ISSUE THREAD

**Issue by LMS235** [dokufreaks/plugin-cloud#83]
After switch to PHP8.1

PHP Warning:  Undefined array key "showCount" in <xxx>/wiki/lib/plugins/cloud/syntax.php on line 138

**Comment by dregad** [comment]
Also:
Warning: Undefined variable $conf in /wiki/lib/plugins/cloud/syntax.php on line 161

**Comment by dregad** [comment]
And a couple more

Warning: Undefined array key 1 in /wiki/lib/plugins/cloud/syntax.php on line 39
Warning: Undefined array key 1 in /wiki/lib/plugins/cloud/syntax.php on line 41
